### ISSUE TITLE
Can't get it to work :(

### ISSUE THREAD

**Issue by AlexZhidkov** [EWSoftware/VSSpellChecker#155]
I installed version 2017.12.29.0 on my VS Enterprise 2017.
Spell checker doesn't work when I type. When I try to Spell Check Active Document, I get "No text editor is selected, the spell checker is currently disabled, or the file is excluded..." message. I've checked all of these and can't find the problem. I tried to uninstall/reinstall extention but it didn't help. What can I do to find the problem?

**Comment by EWSoftware** [comment]
The Spell Check as You Type option can be turned off in any configuration file (global, solution, project, folder, or file).  If you've got any other configuration files besides the global one, check those to ensure it's not disabled in one of them.

The tool window is dependent on selection change notifications to know which file is currently active.  I suppose if you've disabled tracking the active solution explorer item it might disable it though I haven't seen it do that in the past that I recall and I don't think it's necessary for that to work.  Check Tools | Options, Projects and Solutions, and see if "Track Active Item in Solution Explorer" is disabled.  If it is, turn it on and see if that makes a difference.

I'm not sure why else it wouldn't just work.  Solution/project spell checking should work regardless of the interactive setting.

**Comment by AlexZhidkov** [comment]
Spell Check Solution/Project is not finding any misspelled words. 
What's interesting it highlights everything as misspelled in Team Explorer - Changes - Commit message box.
![image](https://user-images.githubusercontent.com/8213739/38591835-576c122e-3d6b-11e8-957f-348aa3dc6868.png)

How can I uninstall and clear everything to install it fresh again?

**Comment by EWSoftware** [comment]
The WPF text boxes are handled independently of the tool windows and don't interact with the active solution/project.  However, if that package is registered and working, the other should be as well.  If it's indicating that everything is misspelled, you might have a non-English dictionary selected as the default.  Right clicking on one of the misspellings will show you the suggestions and the dictionary language it comes from.

You can try uninstalling the extension, resetting the Visual Studio settings (Tools | Import and Export Settings, and select Reset all settings).  If it's a corrupted MEF cache or something related, that should resolve it and it should work once installed after that.  You can also delete the content of the *%LOCALAPPDATA%\EWSoftware\Visual Studio Spell Checker* folder.  That will get rid of any modified global configuration settings.

**Comment by AlexZhidkov** [comment]
I've done all that and it still doesn't work :( 
When I right click misspelling in the WPF box it says "No Suggestions" and it doesn't show any dictionary. I haven't touched any settings since reinstalling.
![image](https://user-images.githubusercontent.com/8213739/38658333-49431ff2-3e57-11e8-89ee-60b9b5a8f39a.png)

**Comment by EWSoftware** [comment]
Sorry, I don't know what else to tell you.  I haven't seen this before.

**Comment by AlexZhidkov** [comment]
It's a shame :( I really like your spell checker. I might try to reinstall VS when I get a chance. Thanks for you help anyway. 👍

**Comment by EWSoftware** [comment]
One thing I hadn't thought of.  If Visual Studio isn't up to date, you might try installing the latest update (15.6.6).  The latest release of the spell checker needs at least version 15.3.  I'm not aware of any breaking changes in Visual Studio after that but anything is possible.

**Comment by AlexZhidkov** [comment]
My Visual Studio Enterprise 2017 is version 15.6.6. I keep it updated.
I haven't reinstalled it yet and SpellChecker still doesn't work.

**Comment by AlexZhidkov** [comment]
Update: It works for me when I run VS as administrator. Still dosn't work normally. Must be something locked down by my org security. Is there a way to go around this?

**Comment by EWSoftware** [comment]
You can probably install the package as an administrator and install it for all users.  Download it from the [Releases Page](https://github.com/EWSoftware/VSSpellChecker/releases) or the Marketplace and then run VSIXInstaller.exe with the /admin command line option.  That should install it for all users, admin or not.  You can find the tool in %ProgramFiles(x86)%\Microsoft Visual Studio\2017\Professional\Common7\IDE.  If that works, the only thing to be aware of is that extensions installed for all users don't auto-update so you need to install any future updates manually the same way.
